"""empty message

Revision ID: 2bcc10571d68
Revises: 
Create Date: 2019-12-30 15:09:43.848136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bcc10571d68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design', sa.Column('design_content', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design', 'design_content')
    # ### end Alembic commands ###
